### ISSUE TITLE
Ultrasonic Range Finder code

### ISSUE THREAD

**Issue by AlecMcC** [SWRRoboticsTeam/49627A-Robot-Code#44]
Build on the code we have for the Ultrasonic Range Finder to try and get it to work with the robot

**Comment by ChristianWesselborg** [comment]
I think its a problem with the interface and cables as opposed to the code.  Let's try a simple bare bones code to test just the interface (no controller configuration).

**Comment by nvertucci-swr** [comment]
Be sure to include LABELS and MILESTONES for issues.
